services:
  nginx:
    image: jc21/nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt

  sysvisual-db:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ImVe3nix!ยง"
      MONGO_INITDB_DATABASE: sysvisual
    networks:
      - sysvisual

  sysvisual:
    image: veenixdev/sysvisual
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - sysvisual/.env.prod
    networks:
      - nginx
      - sysvisual

  lasermatti:
    image: veenixdev/lasermatti
    restart: unless-stopped
    ports:
      - "5174:80"
    networks:
      - nginx

  admin-board:
    image: veenixdev/admin-board
    restart: unless-stopped
    ports:
      - "5173:80"
    networks:
      - nginx

networks:
  nginx:
  sysvisual: