version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - "127.0.0.1:27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: lasermatti

  backend:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
#    volumes:
#      - product-images:/app/upload
  
  frontend:
    build:
      context: ../web_new
      dockerfile: ../web_new/Dockerfile
    ports:
      - "127.0.0.1:3000:5173"
    volumes:
      - type: volume
        source: product-images
        target: /app/public/products

  frontent-admin:
    build:
      context: ../web_admin
      dockerfile: ../web_admin/Dockerfile
    ports:
      - "127.0.0.1:3001:5173"

volumes:
  product-images: