GET http://localhost:8080/products HTTP/1.1
Host: localhost

###

POST http://localhost:8080/product
Content-Type: application/json
Cookie: token=WxMF9iHYGmtKE3wfFW4n1G9XqHxqwmVoZmIPHjpiqu0kPpIs30s50p4SV747LqdHYjqtyN94hO0OBNNBFPoyKar1cliLoaY7oOqX31Y1b0Lro0qHzGnCop0gMb8hD2MO

{
  "title": "Test product2",
  "description": "Test description",
  "price": 1000,
  "image": "testImage"
}